spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartfirehub
    username: app
    password: app

org:
  jobrunr:
    dashboard:
      enabled: true
      port: 8000

app:
  jwt:
    secret: dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBIUzI1NiBhbGdvcml0aG0gdGhhdCBpcyBhdCBsZWFzdCAyNTYgYml0cw==
