spring:
  application:
    name: smart-fire-hub
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 29
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

org:
  jobrunr:
    background-job-server:
      enabled: true
      delete-succeeded-jobs-after: 720h
      permanently-delete-deleted-jobs-after: 2160h
    dashboard:
      enabled: false

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: 1800000
    refresh-expiration: 604800000
  encryption:
    master-key: ${ENCRYPTION_MASTER_KEY}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
